'use client';
import { useEffect, useMemo, useState } from 'react';
import { ArrowDown, ArrowRight, ArrowUpRight, BookOpen, Check, ChevronLeft, ChevronRight, CircleHelp, Clock3, Download, ExternalLink, GitBranch, Layers, Lightbulb, RotateCcw, Search, ShieldCheck, SlidersHorizontal, Target, X } from 'lucide-react';
import StudyPriorities from '@/components/StudyPriorities';
import FlowChart from '@/components/FlowChart';
import ChessBoard from '@/components/ChessBoard';
import ImportDialog from '@/components/ImportDialog';
import { branches, filterGames, lineLabel, matchesPath, mergeGames, moveLabel, openingFor, outcome, rate, stats, type Game, type Library, type Side, type Stats } from '@/lib/chess';
import { DEMO_GAMES } from '@/lib/demo';
import { readLibrary, saveLibrary } from '@/lib/storage';

const EMPTY_GAMES: Game[] = [];

function ResultsBar({value,labels=false}:{value:Stats;labels?:boolean}) {
  return <div className="results-wrap"><div className="results-bar" role="img" aria-label={`${value.win} wins, ${value.draw} draws, ${value.loss} losses`} title={`${value.win} wins (${rate(value.win,value.total).toFixed(1)}%), ${value.draw} draws (${rate(value.draw,value.total).toFixed(1)}%), ${value.loss} losses (${rate(value.loss,value.total).toFixed(1)}%)`}>
    <span className="bar-win" style={{width:`${rate(value.win,value.total)}%`}}/><span className="bar-draw" style={{width:`${rate(value.draw,value.total)}%`}}/><span className="bar-loss" style={{width:`${rate(value.loss,value.total)}%`}}/>
  </div>{labels&&<div className="bar-labels"><span>{rate(value.win,value.total).toFixed(1)}% W</span><span>{rate(value.draw,value.total).toFixed(1)}% D</span><span>{rate(value.loss,value.total).toFixed(1)}% L</span></div>}</div>;
}
function StatCard({label,value,note,kind}:{label:string;value:string;note:string;kind?:string}) {return <div className={`stat-card ${kind??''}`}><span className="stat-label">{kind&&<i/>}{label}</span><strong>{value}</strong><small>{note}</small></div>;}

export default function Home(){
  const [library,setLibrary]=useState<Library|null>(null);const [loaded,setLoaded]=useState(false);const [sample,setSample]=useState(true);
  const [side,setSide]=useState<Side>('black');const [speed,setSpeed]=useState('all');const [days,setDays]=useState('0');const [rated,setRated]=useState(false);const [path,setPath]=useState<string[]>([]);const [depth,setDepth]=useState(2);
  const [resultFilter,setResultFilter]=useState('all');
  const [activeTab,setActiveTab]=useState<'explorer'|'games'|'guide'|'study'>('explorer');const [importOpen,setImportOpen]=useState(false);const [notice,setNotice]=useState('');const [search,setSearch]=useState('');const [page,setPage]=useState(1);const [sort,setSort]=useState('games');const [confirmClear,setConfirmClear]=useState(false);
  useEffect(()=>{let live=true;readLibrary().then(value=>{if(live&&value){setLibrary(value);setSample(false);}}).catch(()=>{if(live)setNotice('Browser storage is unavailable. You can still explore and import games for this session.');}).finally(()=>{if(live)setLoaded(true);});return()=>{live=false;};},[]);
  const games=sample?DEMO_GAMES:library?.games??EMPTY_GAMES;const username=sample?'demo_player':library?.username??'';
  const filtered=useMemo(()=>filterGames(games,username,side,speed,Number(days),rated),[games,username,side,speed,days,rated]);
  const selected=useMemo(()=>filtered.filter(game=>matchesPath(game,path)),[filtered,path]);
  const totals=useMemo(()=>stats(filtered,side),[filtered,side]);const current=useMemo(()=>stats(selected,side),[selected,side]);
  const next=useMemo(()=>branches(selected,path,side),[selected,path,side]);
  const sorted=useMemo(()=>[...next].sort((a,b)=>sort==='wins'?rate(b.stats.win,b.stats.total)-rate(a.stats.win,a.stats.total):sort==='losses'?rate(b.stats.loss,b.stats.total)-rate(a.stats.loss,a.stats.total):b.stats.total-a.stats.total),[next,sort]);
  const opening=useMemo(()=>openingFor(path),[path]);const ended=selected.filter(g=>g.moves.length===path.length).length;
  const weakest=next.filter(b=>b.stats.total>=10).sort((a,b)=>rate(b.stats.loss,b.stats.total)-rate(a.stats.loss,a.stats.total))[0];
  const gameRows=useMemo(()=>selected.filter(g=>(resultFilter==='all'||outcome(g,side)===resultFilter)&&`${g.white} ${g.black} ${lineLabel(g.moves.slice(0,12))}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>b.date-a.date),[selected,search,resultFilter,side]);
  function select(nextPath:string[]){setPath(nextPath);setPage(1);}
  function resetFilters(){setResultFilter('all');setSpeed('all');setDays('0');setRated(false);select([]);}
  async function imported(user:string,incoming:Game[],skipped:number){
    const previous=library?.username.toLowerCase()===user.toLowerCase()?library.games:[];
    const combined=mergeGames(previous,incoming);const value={username:user,games:combined,importedAt:Date.now()};
    let message=`${(combined.length-previous.length).toLocaleString()} new games imported. ${combined.length.toLocaleString()} games in your library.${skipped?` ${skipped} unsupported or unmatched records skipped.`:''}`;
    try{await saveLibrary(value);}catch{message+=' Browser storage is unavailable; this import will last for this session only.';}
    setLibrary(value);setSample(false);resetFilters();setActiveTab('explorer');setNotice(message);
  }
  async function clearLibrary(){try{await saveLibrary(null);setLibrary(null);setSample(true);resetFilters();setConfirmClear(false);setNotice('Your saved library has been removed from this browser.');}catch{setNotice('Could not remove the saved library. Please try again.');}}
  const nav=[{id:'explorer',label:'Opening explorer',icon:GitBranch},{id:'study',label:'Study priorities',icon:Target},{id:'games',label:'Game library',icon:BookOpen},{id:'guide',label:'How to read your games',icon:CircleHelp}] as const;
  return <div className="app-shell">
    <aside className="sidebar"><button className="brand" onClick={()=>{setActiveTab("explorer");select([]);}} aria-label="Opening Lines home"><span className="brand-knight">♞</span><span>opening<span className="brand-second">lines<span className="brand-dot">.</span></span></span></button>
      <div className="sidebar-section-label">YOUR CHESS, UNDERSTOOD</div><nav aria-label="Main navigation">{nav.map(item=><button key={item.id} className={activeTab===item.id?'nav-item active':'nav-item'} onClick={()=>setActiveTab(item.id)} aria-current={activeTab===item.id?'page':undefined}><item.icon size={18}/><span>{item.label}</span>{activeTab===item.id&&<span className="nav-dot"/>}</button>)}</nav>
      <div className="sidebar-note"><div className="note-icon"><Lightbulb size={20}/></div><h3>Find your next good move.</h3><p>A little reflection on your own games goes a long way.</p><div className="mini-board" aria-hidden="true">{Array.from({length:24},(_,i)=><span key={i} className={(Math.floor(i/6)+i%6)%2?'filled':''}>{i===14?'♞':''}</span>)}</div></div>
      <div className="sidebar-bottom"><span className="local-indicator"/><span>Made for your own journey</span><small>One move at a time.</small></div>
    </aside>
    <div className="main-shell"><header className="topbar"><div className="topbar-location"><GitBranch size={17}/><span>{activeTab==='explorer'?'Opening explorer':activeTab==='games'?'Game library':activeTab==='study'?'Study priorities':'A little guidance'}</span></div><div className="topbar-actions"><span className={`source-chip ${sample?'sample':''}`}><i/>{sample?'Sample library':username}</span><button className="primary-button" onClick={()=>setImportOpen(true)} disabled={!loaded}><Download size={16}/><span>Import games</span></button></div></header>
      <nav className="mobile-nav" aria-label="Mobile navigation">{nav.map(item=><button key={item.id} className={activeTab===item.id?"active":""} onClick={()=>setActiveTab(item.id)} aria-current={activeTab===item.id?"page":undefined}>{item.id==="guide"?"How it works":item.label}</button>)}</nav>
      <main>
        {notice&&<div className="toast" role="status"><Check size={16}/><span>{notice}</span><button className="icon-button" onClick={()=>setNotice('')} aria-label="Dismiss message"><X size={16}/></button></div>}
        {activeTab!=='study'&&<div className="page-heading"><div><div className="eyebrow">{activeTab==='explorer'?'LESS GUESSWORK. MORE UNDERSTANDING.':activeTab==='games'?'THE GAMES BEHIND THE NUMBERS':'GET TO KNOW YOUR REPERTOIRE'}</div><h1>{activeTab==='explorer'?'Your games. A clearer plan.':activeTab==='games'?'Every game is a lesson.':'Follow the moves. Find the patterns.'}</h1><p>{activeTab==='explorer'?'See where your openings lead, and where there’s room to grow.':activeTab==='games'?'Revisit the games that make up each branch of your opening tree.':'A practical guide to making the most of your own chess history.'}</p></div><span className="heading-emblem" aria-hidden="true">♘</span></div>}
        {sample&&<div className="demo-banner"><div><span className="demo-tag">TAKE A LOOK AROUND</span><p>You’re exploring a sample library. Bring your own games to make it personal.</p></div><button className="text-button" onClick={()=>setImportOpen(true)}>Import from Lichess <ArrowRight size={16}/></button></div>}
        {activeTab!=='guide'&&<>
          <div className="filterbar"><div className="color-filter"><span>I’m playing as</span><div className="segmented"><button className={side==='white'?'selected':''} onClick={()=>{setSide('white');select([]);}} aria-pressed={side==='white'}><span className="piece-dot white-dot"/>White</button><button className={side==='black'?'selected':''} onClick={()=>{setSide('black');select([]);}} aria-pressed={side==='black'}><span className="piece-dot black-dot"/>Black</button></div></div><div className="other-filters"><label className="select-control"><Clock3 size={14}/><select aria-label="Time control" value={speed} onChange={e=>{setSpeed(e.target.value);select([]);}}><option value="all">All time controls</option>{['ultraBullet','bullet','blitz','rapid','classical','correspondence','unknown'].map(s=><option key={s} value={s}>{s==='ultraBullet'?'Ultrabullet':s==='unknown'?'Unknown time control':s[0].toUpperCase()+s.slice(1)}</option>)}</select></label><label className="select-control"><select aria-label="Date range" value={days} onChange={e=>{setDays(e.target.value);select([]);}}><option value="0">All dates</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option><option value="365">Last year</option></select></label><label className="rated-filter"><input type="checkbox" checked={rated} onChange={e=>{setRated(e.target.checked);select([]);}}/>Rated only</label>{(speed!=='all'||days!=='0'||rated)&&<button className="icon-button" onClick={resetFilters} title="Clear filters" aria-label="Clear filters"><RotateCcw size={15}/></button>}</div></div>
          {activeTab!=='study'&&<div className="stats-grid"><StatCard label="Games as this color" value={totals.total.toLocaleString()} note={`${sample?'Sample games':'Imported games'} · ${side}`}/><StatCard label="Win rate" value={`${rate(totals.win,totals.total).toFixed(1)}%`} note={`${totals.win.toLocaleString()} wins`} kind="win"/><StatCard label="Draw rate" value={`${rate(totals.draw,totals.total).toFixed(1)}%`} note={`${totals.draw.toLocaleString()} draws`} kind="draw"/><StatCard label="Loss rate" value={`${rate(totals.loss,totals.total).toFixed(1)}%`} note={`${totals.loss.toLocaleString()} losses`} kind="loss"/></div>}
        </>}
        {activeTab==='study'&&<StudyPriorities games={filtered} side={side} scope={path} onScope={select} onExplore={p=>{select(p);setActiveTab('explorer');}} onReview={p=>{select(p);setResultFilter('loss');setSearch('');setActiveTab('games');}}/>}
        {activeTab==='explorer'&&<>
          <button className="study-entry" onClick={()=>setActiveTab('study')}><Target size={20}/><span><strong>Find your highest-priority study lines</strong><small>{path.length?'Search for recurring trouble within this opening.':'Compare branches, find repeated losses, and check a move with Stockfish.'}</small></span><span>Study priorities</span></button>
          <div className="explorer-grid"><section className="panel flow-panel"><div className="panel-heading"><div><h2>Your opening paths <span className="small-pill">{selected.length.toLocaleString()} games</span></h2><p>Follow a branch to see what happens next.</p></div><label className="depth-picker"><SlidersHorizontal size={14}/><select aria-label="Number of half-moves displayed" value={depth} onChange={e=>setDepth(Number(e.target.value))}><option value={1}>1 move ahead</option><option value={2}>2 moves ahead</option><option value={3}>3 moves ahead</option></select></label></div>
            <div className="breadcrumbs" aria-label="Current move sequence"><button onClick={()=>select([])} className={!path.length?'current':''}>Starting position</button>{path.map((m,i)=><span key={i}><ChevronRight size={12}/><button className={i===path.length-1?'current':''} onClick={()=>select(path.slice(0,i+1))}>{moveLabel(m,i)}</button></span>)}{path.length>0&&<button className="breadcrumb-reset" onClick={()=>select([])} title="Reset to starting position"><RotateCcw size={13}/>Reset</button>}</div>
            <FlowChart games={selected} path={path} side={side} depth={depth} onSelect={select}/>
            <div className="flow-footer"><span><span className="width-symbol"/>Wider paths mean more games</span><span>Click a move to explore <ArrowUpRight size={13}/></span></div>
          </section>
          <aside className="panel position-panel"><div className="position-header"><span className="eyebrow">ON THE BOARD</span><span className="small-pill">{path.length%2?'Black':'White'} to move</span></div><h2>{path.length?opening.name:'The starting position'}</h2><p className="position-line">{path.length?lineLabel(path):'The beginning of every possibility.'}</p><ChessBoard path={path} side={side}/><div className="board-actions"><span>Viewing as {side}</span><button className="icon-button" disabled={!path.length} onClick={()=>select(path.slice(0,-1))} aria-label="Go back one half-move" title="Go back one move"><ChevronLeft size={17}/></button><button className="icon-button" disabled={!path.length} onClick={()=>select([])} aria-label="Reset board"><RotateCcw size={14}/></button></div><div className="position-results"><div><strong>{current.total.toLocaleString()}</strong><span>games reached this position</span></div><ResultsBar value={current}/><div className="wdl-detail">{(['win','draw','loss'] as const).map(k=><div key={k}><span className={`result-dot ${k}`}/><strong>{rate(current[k],current.total).toFixed(1)}%</strong><small>{current[k]} {k==='loss'?'losses':`${k}s`}</small></div>)}</div></div>
            <p className="perspective-note"><ShieldCheck size={13}/>All results from your perspective.</p>
          </aside></div>
          {!path.length&&filtered.some(g=>matchesPath(g,['e4','c6','d4','d5']))&&<button className="caro-shortcut" onClick={()=>select(['e4','c6','d4','d5'])}><div className="shortcut-icon"><GitBranch size={18}/></div><div><strong>A closer look at the Caro-Kann</strong><span><b>1. e4 c6 2. d4 d5</b> · Compare the Advance, Exchange, and other continuations.</span></div><ArrowRight size={18}/></button>}
          <section className="panel next-panel" id="next-moves"><div className="panel-heading"><div><h2>{path.length?'What happens next?':'The first move, at a glance'}</h2><p>{path.length%2?'Black':'White'}’s next moves · your results as {side}</p></div><label className="sort-control"><ArrowDown size={13}/><select value={sort} onChange={e=>setSort(e.target.value)} aria-label="Sort next moves"><option value="games">Most played</option><option value="wins">Highest win rate</option><option value="losses">Highest loss rate</option></select></label></div>
            <div className="table-scroll"><table className="moves-table"><thead><tr><th>MOVE & OPENING</th><th>GAMES</th><th>FREQUENCY</th><th>YOUR WIN / DRAW / LOSS</th><th><span className="sr-only">Explore</span></th></tr></thead><tbody>{sorted.map(branch=><tr key={branch.move} onClick={()=>select(branch.path)}><td><button className="move-table-button" onClick={e=>{e.stopPropagation();select(branch.path);}}><span className="move-token">{moveLabel(branch.move,path.length)}</span><span><strong>{branch.name}</strong><small>{lineLabel(branch.path)}{branch.eco?` · ${branch.eco}`:''}</small></span></button></td><td><strong>{branch.stats.total}</strong>{branch.stats.total<10&&<small className="small-sample">Small sample</small>}</td><td>{rate(branch.stats.total,current.total).toFixed(1)}%</td><td><ResultsBar value={branch.stats} labels/></td><td><ChevronRight size={16}/></td></tr>)}</tbody></table></div>
            {!next.length&&<div className="empty-state"><Layers size={24}/><h3>{selected.length?'You’ve reached the end of these games.':'No matching games yet.'}</h3><p>{selected.length?'Step back to explore a different branch.':'Try clearing filters or importing more games.'}</p><button className="text-button" onClick={()=>path.length?select(path.slice(0,-1)):resetFilters()}>{path.length?'Go back one move':'Clear filters'} <ArrowRight size={14}/></button></div>}
            {ended>0&&<p className="table-note">{ended} {ended===1?'game ends':'games end'} at this position and have no next move.</p>}
          </section>
          {weakest&&<div className="insight-card"><Lightbulb size={23}/><div><span className="eyebrow">A PLACE TO START</span><p>You lost <strong>{rate(weakest.stats.loss,weakest.stats.total).toFixed(0)}%</strong> of your <strong>{weakest.stats.total} games</strong> after <strong>{moveLabel(weakest.move,path.length)}</strong>. Revisit a few to see where things went off track.</p><span>Game results are a starting point for study, not an engine evaluation of the move.</span></div><button className="text-button" onClick={()=>{select(weakest.path);setResultFilter('loss');setSearch('');setActiveTab('games');}}>Review these games<ArrowRight size={15}/></button></div>}
        </>}
        {activeTab==='games'&&<section className="panel library-panel"><div className="panel-heading"><div><h2>{path.length?'Games in this line':'Your game library'} <span className="small-pill">{gameRows.length}</span></h2><p>{path.length?lineLabel(path):sample?'Synthetic sample games for exploring the app.':'Your imported, completed standard-chess games.'}</p></div><label className="search-field"><Search size={16}/><input placeholder="Search player or moves…" aria-label="Search games" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/></label></div>{path.length>0&&<button className="text-button library-reset" onClick={()=>select([])}>Show all lines <X size={14}/></button>}<div className="library-result-filter"><label>Show results <select aria-label="Filter game results" value={resultFilter} onChange={e=>{setResultFilter(e.target.value);setPage(1);}}><option value="all">All results</option><option value="win">Wins</option><option value="draw">Draws</option><option value="loss">Losses</option></select></label></div><div className="table-scroll"><table className="games-table"><thead><tr><th>RESULT</th><th>OPPONENT</th><th>OPENING MOVES</th><th>TIME CONTROL</th><th>DATE</th><th>REVIEW</th></tr></thead><tbody>{gameRows.slice((page-1)*20,page*20).map(game=><tr key={game.id}><td><span className={`result-badge ${outcome(game,side)}`}>{outcome(game,side)}</span></td><td><strong>{game[side==='black'?'white':'black']}</strong><small>{game[side==='black'?'whiteRating':'blackRating']??'Unrated'}</small></td><td className="game-line">{lineLabel(game.moves.slice(0,8))}</td><td className="capitalize">{game.speed}</td><td>{game.date?new Date(game.date).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}):'Unknown'}</td><td>{game.url?<a className="external-link" href={game.url} target="_blank" rel="noreferrer">Lichess <ExternalLink size={13}/></a>:<button className="text-button" onClick={()=>{select(game.moves.slice(0,Math.min(8,game.moves.length)));setActiveTab('explorer');}}>Explore<ArrowUpRight size={13}/></button>}</td></tr>)}</tbody></table></div>{!gameRows.length&&<div className="empty-state"><Search size={24}/><h3>No games match this view.</h3><p>Try a different search, color, or date range.</p></div>}<div className="pagination"><span>{gameRows.length?`${(page-1)*20+1}–${Math.min(page*20,gameRows.length)} of ${gameRows.length} games`:'0 games'}</span><div><button className="icon-button" disabled={page===1} onClick={()=>setPage(p=>p-1)} aria-label="Previous page"><ChevronLeft size={18}/></button><button className="icon-button" disabled={page*20>=gameRows.length} onClick={()=>setPage(p=>p+1)} aria-label="Next page"><ChevronRight size={18}/></button></div></div></section>}
        {activeTab==='guide'&&<div className="guide-grid"><section className="panel guide-card"><span className="guide-number">01</span><h2>Start with your own games.</h2><p>Enter a Lichess username to import recent games, or upload a PGN export. Choose the number of games to download. Importing again merges the games without duplicates.</p><button className="text-button" onClick={()=>setImportOpen(true)}>Import your games<ArrowRight size={15}/></button></section><section className="panel guide-card"><span className="guide-number">02</span><h2>Follow the moves, not just the names.</h2><p>Read the chart from left to right. Each step is one move by one player, also called a half-move. Wider ribbons mean more games. Click a move to focus the chart and board on that exact sequence.</p><p>Opening names provide context. If the position has no new name, the last recognized opening stays visible. Different move orders remain separate paths, even if they reach the same position.</p></section><section className="panel guide-card"><span className="guide-number">03</span><h2>Keep your side of the story.</h2><p>Playing Black? A win is a Black win, even when the branch you click is White’s move. Win, draw, and loss rates use completed games that reached that exact path.</p><p>Frequency tells you how often that next move occurred among all games at the selected position. The top cards summarize your filters; the board card summarizes your selected line.</p></section><section className="panel guide-card"><span className="guide-number">04</span><h2>Use the numbers to ask better questions.</h2><p>A low win rate doesn’t prove an opening move is bad. Your opponents, time controls, and later mistakes all matter. Look for repeat patterns and review the full games.</p><p>Fewer than 10 games is marked as a small sample. Use Study priorities to find unusually difficult branches or repeated losses. Its optional Stockfish check evaluates the selected move separately from your game results.</p></section></div>}
        <footer className="page-footer"><span><span className="brand-small">♞</span> A little more understanding, one move at a time.</span><div><a href="https://github.com/lichess-org/chess-openings" target="_blank" rel="noreferrer">Opening names by Lichess <ArrowUpRight size={12}/></a><span>Saved on this device</span></div></footer>
        {library&&<div className="library-controls"><span>{library.games.length.toLocaleString()} saved games · {library.username}</span><button className="text-button" onClick={()=>{setSample(s=>!s);resetFilters();}}>{sample?'Return to my games':'Explore sample games'}</button>{confirmClear?<><span>Remove saved games from this browser?</span><button className="text-button danger" onClick={clearLibrary}>Remove library</button><button className="text-button" onClick={()=>setConfirmClear(false)}>Cancel</button></>:<button className="text-button muted" onClick={()=>setConfirmClear(true)}>Clear saved library</button>}</div>}
      </main>
    </div>
    {importOpen&&<ImportDialog library={library} onClose={()=>setImportOpen(false)} onImport={imported}/>}
  </div>;
}
