'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { Activity, BookOpen, ChevronDown, ChevronUp, Cpu, GitBranch, LoaderCircle, Search, SlidersHorizontal, Target, TrendingDown, X } from 'lucide-react';
import ChessBoard from './ChessBoard';
import { lineLabel, matchesPath, moveLabel, openingFor, rate, type Game, type Side, type Stats } from '@/lib/chess';
import { buildStudyTree, rankStudy, type MoveOwner, type StudyCandidate, type StudyMode } from '@/lib/priorities';
import { checkBranch, scoreText, type EngineResult } from '@/lib/engine';
import { ratingCohort, ratingPools, signedPoints } from '@/lib/ratings';
import { RatingComparison, RatingDetails } from './RatingDetails';

export type RatingReview = {pool:string;days:number;includeProvisional:boolean};

const pct=(x:number)=>(100*x).toFixed(1)+'%';
function Breakdown({stats}:{stats:Stats}){return <div className="study-wdl"><span>{stats.win} wins</span><span>{stats.draw} draws</span><span>{stats.loss} losses</span></div>;}
function EngineCheck({candidate,side}:{candidate:StudyCandidate;side:Side}){
  const [result,setResult]=useState<EngineResult|null>(null);const [progress,setProgress]=useState('');const [error,setError]=useState('');const abort=useRef<AbortController|null>(null);
  useEffect(()=>()=>abort.current?.abort(),[]);
  async function run(){
    const controller=new AbortController();abort.current=controller;setError('');setProgress('Starting analysis…');
    try{setResult(await checkBranch(candidate.path,side,controller.signal,setProgress));}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Could not analyze this position.');}finally{if(!controller.signal.aborted)setProgress('');}
  }
  const position=openingFor(candidate.path);const bestPrefix=result?.kind==='my-move'?candidate.path.slice(0,-1):candidate.path;
  const evalDescription=result?.played?(result.drop===null?'A mating line is involved; compare the evaluations below.':result.drop>=1?`This search finds an evaluation drop of about ${result.drop.toFixed(2)} after your move.`:result.drop>=.3?`This search finds a modest evaluation drop of about ${result.drop.toFixed(2)}.`:'This search found little or no evaluation loss from your move. Your game losses may have happened later.'):'Positive evaluations favor you; negative evaluations favor your opponent.';
  return <section className="engine-check" aria-labelledby="engine-heading"><div className="study-subheading"><Cpu size={18}/><h3 id="engine-heading">Check the chess, too</h3></div>
    <p>{candidate.owner==='mine'?'Compare your move with Stockfish’s best available move from the same position.':'See how Stockfish evaluates the position and which reply it suggests for you.'}</p>
    {!progress&&<button className="study-action primary" onClick={run}><Cpu size={16}/>{result?'Analyze again':'Check with Stockfish'}</button>}
    {!!progress&&<div className="engine-progress" role="status"><LoaderCircle size={17} className="spin"/><span>{progress}</span><button onClick={()=>{abort.current?.abort();setProgress('');}} className="study-action">Cancel</button></div>}
    {error&&<p className="error-message" role="alert">{error}</p>}
    {result&&<div className="engine-result"><div className="engine-scores"><div><span>{result.kind==='my-move'?'Best available':'Current position'}</span><strong>{scoreText(result.best)}</strong><small>Depth {result.best.depth}</small></div>{result.played&&<div><span>After your move</span><strong>{scoreText(result.played)}</strong><small>Depth {result.played.depth}</small></div>}</div><p>{evalDescription}</p>{result.bestLine.length>0&&<div className="engine-line"><span>{result.kind==='my-move'?'Suggested alternative / continuation':'Suggested reply / continuation'}</span><strong>{lineLabel([...bestPrefix,...result.bestLine])}</strong></div>}<small>Stockfish 19 Lite · up to depth 18 or 1.8 seconds per search. A quick estimate; deeper analysis may change it. Numeric evaluations use the engine’s pawn-unit scale, from your side.</small></div>}
    <div className="engine-links"><a href={`https://lichess.org/analysis/standard/${position.fen.replace(/ /g,'_')}`} target="_blank" rel="noreferrer">Open full Lichess analysis</a><a href="/engine/Copying.txt" target="_blank" rel="noreferrer">Engine license</a><a href="/engine/stockfish-source.tar.gz" download>Engine source</a></div><small className="engine-local">Runs on this device, only when you ask.</small>
  </section>;
}

export default function StudyPriorities({games,side,scope,days,onScope,onExplore,onReview,onImport}:{games:Game[];side:Side;scope:string[];days:number;onScope:(path:string[])=>void;onExplore:(path:string[])=>void;onReview:(path:string[],rating?:RatingReview)=>void;onImport:()=>void}){
  const [mode,setMode]=useState<StudyMode>('rating');const [minGames,setMinGames]=useState(5);const [maxMoves,setMaxMoves]=useState(12);const [minMove,setMinMove]=useState(1);const [owner,setOwner]=useState<MoveOwner>('all');const [collapse,setCollapse]=useState(true);const [selectedKey,setSelectedKey]=useState('');const [showHow,setShowHow]=useState(false);const [limit,setLimit]=useState(20);const [search,setSearch]=useState('');
  const [pool,setPool]=useState('');const [ratingDays,setRatingDays]=useState(90);const [includeProvisional,setIncludeProvisional]=useState(false);const [now]=useState(()=>Date.now());
  const isRating=mode==='rating'||mode==='rating-net';
  const pools=useMemo(()=>ratingPools(games),[games]);const currentPool=pools.includes(pool)?pool:pools[0]??'';
  const ratingGames=useMemo(()=>ratingCohort(games,currentPool,ratingDays,includeProvisional,now),[games,currentPool,ratingDays,includeProvisional,now]);
  const studyGames=isRating?ratingGames:games;
  const tree=useMemo(()=>buildStudyTree(studyGames,side,scope,maxMoves),[studyGames,side,scope,maxMoves]);
  const missingChanges=mode==='rating-net'&&tree.total>0&&tree.root.rating.changeCount===0;
  const reviewDays=days&&ratingDays?Math.min(days,ratingDays):days||ratingDays;
  const ranking=useMemo(()=>rankStudy(tree,side,{mode,minGames,owner,collapse,minMove}),[tree,side,mode,minGames,owner,collapse,minMove]);
  // Only qualifying nodes get names; never replay every game to build the tree.
  const rows=useMemo(()=>{const query=search.toLowerCase().trim();return query?ranking.candidates.filter(c=>`${lineLabel(c.path)} ${openingFor(c.path).name}`.toLowerCase().includes(query)):ranking.candidates;},[ranking,search]);
  const chosen=rows.find(c=>c.path.join(' ')===selectedKey)??rows[0];
  const choices=[{id:'rating',label:'Rating impact',description:'Results vs opponent strength',icon:TrendingDown},{id:'contrast',label:'Unusually difficult',description:'More losses than sibling branches',icon:Target},{id:'volume',label:'Frequent losses',description:'Frequency × observed loss rate',icon:Activity},{id:'perfect',label:'Lost every game',description:'Earliest 100% loss branches',icon:Search}] as const;
  const quickScopes=useMemo(()=>[{name:'French',path:['e4','e6']},{name:'Caro-Kann',path:['e4','c6']},{name:'Sicilian',path:['e4','c5']},{name:'Scandinavian',path:['e4','d5']}].filter(o=>studyGames.some(g=>matchesPath(g,o.path))),[studyGames]);
  const name=chosen?openingFor(chosen.path):null;
  const allLossAt=useMemo(()=>rankStudy(tree,side,{mode:'perfect',minGames,owner,collapse:false,minMove}).candidates[0],[tree,side,minGames,owner,minMove]);
  return <section className="study-surface" aria-label="Study priorities">
    <div className="study-intro"><div><h2>What should you work on next?</h2><p>Find repeated trouble spots, then check the position before changing your repertoire.</p></div><button className="study-action" onClick={()=>setShowHow(s=>!s)} aria-expanded={showHow}>How this is ranked {showHow?<ChevronUp size={15}/>:<ChevronDown size={15}/>}</button></div>
    <div className="study-scope"><span>{scope.length?'Focused on:':'Searching:'}</span><strong>{scope.length?lineLabel(scope):'All your openings'}</strong>{scope.length>0&&<button onClick={()=>onScope([])} aria-label="Study all openings"><X size={15}/>All openings</button>}<span>{tree.total.toLocaleString()} {isRating?`rated ${currentPool} `:''}games as {side}</span></div>
    {!scope.length&&<div className="study-quick-scopes" aria-label="Focus on an opening">{quickScopes.map(o=><button key={o.name} onClick={()=>onScope(o.path)}>{o.name} · {lineLabel(o.path)}</button>)}</div>}
    <div className="study-modes" role="group" aria-label="Priority ranking">{choices.map(choice=><button key={choice.id} aria-pressed={choice.id==='rating'?isRating:mode===choice.id} className={(choice.id==='rating'?isRating:mode===choice.id)?'selected':''} onClick={()=>{setMode(choice.id);setLimit(20);}}><choice.icon size={20}/><span><strong>{choice.label}</strong><small>{choice.description}</small></span></button>)}</div>
    {isRating&&<section className="rating-controls" aria-label="Rating priority settings">
      <div className="rating-control-fields"><label>Rank by<select value={mode} onChange={e=>{setMode(e.target.value as StudyMode);setLimit(20);}}><option value="rating">Below expected score</option><option value="rating-net">Net rating points lost</option></select></label><label>Rating pool<select value={currentPool} onChange={e=>setPool(e.target.value)} disabled={!pools.length}>{!pools.length&&<option value="">No rated games</option>}{pools.map(p=><option key={p} value={p}>{p==='ultraBullet'?'Ultrabullet':p[0].toUpperCase()+p.slice(1)}</option>)}</select></label><label>Rating window<select value={ratingDays} onChange={e=>setRatingDays(Number(e.target.value))}><option value={30}>Last 30 days</option><option value={90}>Last 90 days</option><option value={365}>Last year</option><option value={0}>All dates</option></select></label></div>
      <label className="rating-provisional"><input type="checkbox" checked={includeProvisional} onChange={e=>setIncludeProvisional(e.target.checked)}/>Include games with provisional ratings</label>
      <p>{mode==='rating'?'Ranks frequent branches where you score below the expectation from pre-game ratings. This approximation works without recorded rating changes. Tiny samples are reduced in weight.':'Ranks the largest net rating losses, adding every recorded gain and loss. This view needs the actual change after each game; pre-game ratings alone are not enough. Frequency is already included in the total.'} Uses rated games matching the filters above, this pool, and this window. {includeProvisional?'Provisional ratings are included.':'Games flagged provisional for either player are excluded.'}</p>
      <div className="rating-coverage"><span><b>{tree.root.rating.count}/{tree.total}</b> games have both pre-game ratings · <b>{tree.root.rating.changeCount}/{tree.total}</b> have your recorded rating change saved</span></div>
      {tree.total>0&&tree.root.rating.changeCount<tree.total&&<><small>Lichess can provide rating changes, but older imports and some PGNs do not contain them in your saved library. Re-import from your Lichess username and choose enough games to cover this date range. Existing games are updated without duplicates. Missing changes are never counted as zero.</small><div className="rating-data-actions"><button className="study-action" onClick={onImport}>Re-import from Lichess</button>{mode==='rating-net'&&tree.root.rating.count>=minGames&&<button className="study-action" onClick={()=>{setMode('rating');setSearch('');setLimit(20);}}>Use approximate ranking</button>}</div></>}
    </section>}
    {showHow&&<div className="study-method"><h3>A study queue, not a verdict</h3><p><b>Below expected score:</b> for each rated game, expected score = 1 / (1 + 10^((opponent rating − your rating) / 400)). Actual score is 1 for a win, ½ for a draw, and 0 for a loss. Priority = 100 × (eligible branch games / eligible scope games) × max(0, (total expected score − total actual score) / (eligible branch games + 5)). Five neutral pseudo-games shrink small samples toward zero. The score is a smoothed shortfall per 100 eligible games, not rating points or predicted gains from study.</p><p><b>Net rating points lost:</b> sum your recorded rating changes in the branch, most negative first. Wins and draws count too; no extra frequency multiplier is applied. Each ranking requires the minimum number of games with its needed data. Coverage counts show what is missing.</p><p>Lichess uses Glicko-2, which also considers rating uncertainty and color. Our expected score is a transparent Elo approximation, not a reconstruction of its exact rating calculation. Actual imported rating changes are shown unchanged. Rating pools stay separate. The default 90-day window keeps old problems from dominating; global date filters still apply. Use the opponent-strength breakdown to spot weaknesses hidden by an overall average.</p><p><b>Frequent losses:</b> (games in this branch ÷ games in scope) × branch loss rate. This equals losses in this branch per 100 games in scope. It measures how much of your history this problem touches.</p><p><b>Unusually difficult:</b> frequency × the positive difference between this branch’s smoothed loss rate and the other moves from its exact parent position. Both groups need your minimum sample. Rates are smoothed with five extra games at your overall loss rate so tiny samples carry less weight. Scores describe excess losses per 100 games in scope; they are not predicted wins you could recover.</p><p><b>Lost every game:</b> the earliest node where every game was a loss, with your minimum sample. Its all-loss descendants are redundant and are omitted. A 2/2 or 5/5 record is a clue, not proof that the move caused the losses.</p><p>Forced continuations and a first move you always play are omitted except in Lost every game. By default, related ancestors and descendants are grouped under their highest-ranked finding. Loss counts overlap across branches, so don’t add row scores. Draws are separate from losses. Different move orders remain separate paths; only Rating impact adjusts for opponent strength. None of these rankings can attribute a later mistake to the opening.</p></div>}
    <div className="study-controls"><label>At least<select value={minGames} onChange={e=>setMinGames(Number(e.target.value))}>{[2,3,5,10,20].map(n=><option key={n} value={n}>{n} games</option>)}</select></label><label>From move<select value={minMove} onChange={e=>{const n=Number(e.target.value);setMinMove(n);if(n>maxMoves)setMaxMoves(n);}}>{[1,3,5,8,10].map(n=><option key={n} value={n}>{n}</option>)}</select></label><label>Through move<select value={maxMoves} onChange={e=>{const n=Number(e.target.value);setMaxMoves(n);if(minMove>n)setMinMove(n);}}>{[5,10,12,15,20].map(n=><option key={n} value={n}>{n}</option>)}</select></label><label>Whose move?<select value={owner} onChange={e=>setOwner(e.target.value as MoveOwner)}><option value="all">Either player</option><option value="mine">My decisions</option><option value="opponent">Opponent’s replies</option></select></label><label className="study-collapse"><input type="checkbox" checked={collapse} onChange={e=>setCollapse(e.target.checked)}/>Group related lines</label></div>
    <div className="study-summary"><span>{missingChanges?'Ranking unavailable — rating changes have not been imported':<><b>{ranking.candidates.length}</b> study candidates{ranking.collapsed>0?` · ${ranking.collapsed} overlapping findings grouped`:''}</>}</span><span>{isRating?(mode==='rating'?'Priority = smoothed score shortfall / 100 games':'Most negative net change first'):allLossAt?`First all-loss branch: ${moveLabel(allLossAt.path.at(-1)!,allLossAt.path.length-1)} (${allLossAt.stats.total} games)`:`No all-loss branch with ${minGames}+ games in this range`}</span></div>
    <label className="study-search"><Search size={17}/><input value={search} onChange={e=>{setSearch(e.target.value);setLimit(20);}} placeholder="Filter by opening or moves, e.g. French or e4 e6" aria-label="Filter study candidates"/></label>
    <div className="study-grid"><div className="study-list" aria-label="Ranked opening problems">{rows.slice(0,limit).map((c,i)=>{const opening=openingFor(c.path);return <button key={c.path.join(' ')} aria-pressed={chosen===c} className={`study-row ${chosen===c?'selected':''}`} onClick={()=>{setSelectedKey(c.path.join(' '));if(window.matchMedia('(max-width:900px)').matches)requestAnimationFrame(()=>document.querySelector('.study-detail')?.scrollIntoView({block:'start'}));}}>
      <span className="study-rank">{i+1}</span><div className="study-row-body"><div className="study-row-title"><strong>{moveLabel(c.path.at(-1)!,c.path.length-1)}</strong><span>{c.owner==='mine'?'Your decision':'Opponent’s move'}</span>{c.stats.loss===c.stats.total&&<span className="study-loss-tag">{c.stats.total}/{c.stats.total} losses</span>}</div><p>{opening.name}</p><code>{lineLabel(c.path)}</code><div className="study-row-data"><span>{c.stats.total} games · {pct(c.frequency)} of scope</span>{isRating?<><span>{c.rating.count?`Scored ${pct(c.rating.actual/c.rating.count)} vs ${pct(c.rating.expected/c.rating.count)} expected (${c.rating.count} games)`:'Pre-game ratings unavailable'}</span><span>{c.rating.changeCount?`Net ${signedPoints(c.rating.netChange)} rating points · changes in ${c.rating.changeCount}/${c.stats.total} games`:'Net rating points unavailable — refresh import'}</span></>:<span><b>{pct(c.lossRate)}</b> losses{c.otherLossRate!==null?` vs ${pct(c.otherLossRate)}`:''}</span>}</div>{(isRating?(mode==='rating'?c.rating.count:c.rating.changeCount):c.stats.total)<10&&<small className="study-small-sample">Small sample — use as a lead for review</small>}</div><div className="study-score"><strong>{mode==='rating'?c.ratingPriority.toFixed(2):mode==='rating-net'?signedPoints(c.rating.netChange):mode==='contrast'?c.priority.toFixed(2):mode==='volume'?c.lossShare.toFixed(1):c.stats.total}</strong><span>{mode==='rating'?'shortfall / 100':mode==='rating-net'?'rating points':mode==='contrast'?'priority':mode==='volume'?'losses / 100':'games lost'}</span></div>
    </button>;})}{rows.length>limit&&<button className="study-action load-more" onClick={()=>setLimit(n=>n+20)}>Show 20 more</button>}
      {!rows.length&&<div className="study-empty"><SlidersHorizontal size={28}/><h3>{missingChanges?'No recorded rating changes yet':tree.total?'No branches match this view':'No games in this scope'}</h3><p>{missingChanges?`None of the ${tree.total} games in this view has your rating change saved. This does not mean these openings cost you no rating points. Re-import the games to rank their recorded changes.${tree.root.rating.count>=minGames?' Or use the approximate ranking now: it compares your results with the expectations from the pre-game ratings you already have.':''}`:search?'Try a shorter opening name or just the move notation.':isRating?(!tree.total?'No rated games match this pool, window, and scope. Try a wider window or another pool.':(mode==='rating'?tree.root.rating.count:tree.root.rating.changeCount)<minGames?'Not enough games have the required rating data. Refresh your import or widen the window.':'No branching line has enough data and a negative result under this ranking. Try another scope, minimum sample, or ranking.'):mode==='contrast'?'No branch has enough games on both sides of a worse-than-alternatives comparison. Try Frequent losses, a smaller minimum, or a wider move range.':mode==='perfect'?'No new all-loss branch meets your minimum sample in this range. This does not mean your play was mistake-free.':'Try a wider move range or a different opening scope.'}</p>{missingChanges&&<div className="rating-data-actions"><button className="study-action primary" onClick={onImport}>Re-import from Lichess</button>{tree.root.rating.count>=minGames&&<button className="study-action" onClick={()=>{setMode('rating');setSearch('');setLimit(20);}}>Use approximate ranking</button>}</div>}{mode==='contrast'&&<button className="study-action" onClick={()=>setMode('volume')}>See frequent losses</button>}</div>}
    </div>
    {chosen&&name&&<aside className="study-detail" key={chosen.path.join(' ')+side}><div className="study-detail-heading"><span>{chosen.owner==='mine'?'RECONSIDER YOUR MOVE':'PREPARE FOR THEIR MOVE'}</span><h3>{moveLabel(chosen.path.at(-1)!,chosen.path.length-1)}</h3><p>{name.name}</p><code>{lineLabel(chosen.path)}</code></div><ChessBoard path={chosen.path} side={side}/><div className="study-detail-stats"><strong>{chosen.stats.loss} losses in {chosen.stats.total} games</strong><Breakdown stats={chosen.stats}/><p>You reached this branch in {pct(chosen.frequency)} of the {tree.total} games in scope.</p></div>
      {isRating?<><RatingDetails value={chosen.rating} total={chosen.stats.total}/><RatingComparison candidate={chosen} net={mode==='rating-net'} onExplore={onExplore}/></>:<section className="study-comparison"><h4>At the same decision point</h4><div className="study-compare-row"><span>{moveLabel(chosen.path.at(-1)!,chosen.path.length-1)}</span><b>{pct(chosen.lossRate)} losses</b><span>{chosen.stats.total} games</span></div>{chosen.siblings.map(s=><div key={s.path.join(' ')} className="study-compare-row"><button onClick={()=>onExplore(s.path)}>{moveLabel(s.path.at(-1)!,s.path.length-1)}</button><b>{rate(s.stats.loss,s.stats.total).toFixed(1)}% losses</b><span>{s.stats.total} games</span></div>)}{!chosen.siblings.length&&<p>You haven’t played another move from this exact position in these games.</p>}{chosen.rawGap!==null&&<p>{chosen.rawGap>0?`${(chosen.rawGap*100).toFixed(1)} percentage points more losses than the other branches combined.`:'This branch does not have a higher observed loss rate than the alternatives combined.'}</p>}</section>}
      <div className="study-detail-actions"><button className="study-action primary" onClick={()=>onReview(chosen.path,isRating?{pool:currentPool,days:reviewDays,includeProvisional}:undefined)}><BookOpen size={16}/>{isRating?'Review these games':'Review these losses'}</button><button className="study-action" onClick={()=>onExplore(chosen.path)}><GitBranch size={16}/>Explore line</button><button className="study-action" onClick={()=>onScope(chosen.path)}>Search deeper here</button></div>
      <EngineCheck candidate={chosen} side={side}/>
    </aside>}
    </div>
    <p className="study-footnote">Historical results point to questions worth studying. They don’t establish that an opening move caused a loss. Stockfish checks the selected chess position separately.</p>
  </section>;
}
